/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#ifndef PB_ACTIVATION_PB_H_INCLUDED
#define PB_ACTIVATION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ActivationReq {
    char activity_ai[200];
/* @@protoc_insertion_point(struct:ActivationReq) */
} ActivationReq;

typedef struct _ActivationResp {
    int64_t state;
/* @@protoc_insertion_point(struct:ActivationResp) */
} ActivationResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ActivationReq_init_default               {""}
#define ActivationResp_init_default              {0}
#define ActivationReq_init_zero                  {""}
#define ActivationResp_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */
#define ActivationReq_activity_ai_tag            1
#define ActivationResp_state_tag                 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ActivationReq_fields[2];
extern const pb_field_t ActivationResp_fields[2];

/* Maximum encoded size of messages (where known) */
#define ActivationReq_size                       203
#define ActivationResp_size                      11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ACTIVATION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
