/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#ifndef PB_ADDACTION_PB_H_INCLUDED
#define PB_ADDACTION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _AddActionReq {
    char action_name[200];
    int64_t execute_order;
    int64_t execute_time;
    char arguments[200];
/* @@protoc_insertion_point(struct:AddActionReq) */
} AddActionReq;

typedef struct _AddActionResp {
    int64_t state;
/* @@protoc_insertion_point(struct:AddActionResp) */
} AddActionResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AddActionReq_init_default                {"", 0, 0, ""}
#define AddActionResp_init_default               {0}
#define AddActionReq_init_zero                   {"", 0, 0, ""}
#define AddActionResp_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define AddActionReq_action_name_tag             1
#define AddActionReq_execute_order_tag           2
#define AddActionReq_execute_time_tag            3
#define AddActionReq_arguments_tag               4
#define AddActionResp_state_tag                  1

/* Struct field encoding specification for nanopb */
extern const pb_field_t AddActionReq_fields[5];
extern const pb_field_t AddActionResp_fields[2];

/* Maximum encoded size of messages (where known) */
#define AddActionReq_size                        428
#define AddActionResp_size                       11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ADDACTION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
