/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#include "AddAction.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t AddActionReq_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, AddActionReq, action_name, action_name, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, AddActionReq, execute_order, action_name, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, AddActionReq, execute_time, execute_order, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, AddActionReq, arguments, execute_time, 0),
    PB_LAST_FIELD
};

const pb_field_t AddActionResp_fields[2] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, AddActionResp, state, state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
