/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#include "Connect.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConnectReq_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, ConnectReq, serial_num, serial_num, 0),
    PB_LAST_FIELD
};

const pb_field_t ConnectResp_fields[5] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, ConnectResp, state, state, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ConnectResp, serial_num, state, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, ConnectResp, connect_state, serial_num, 0),
    PB_FIELD(  4, INT64   , REQUIRED, STATIC  , OTHER, ConnectResp, version_code, connect_state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
