/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#include "DeleteAction.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeleteActionReq_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeleteActionReq, action_id, action_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeleteActionResp_fields[2] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, DeleteActionResp, state, state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
