/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#ifndef PB_DELETEACTION_PB_H_INCLUDED
#define PB_DELETEACTION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DeleteActionReq {
    char action_id[200];
/* @@protoc_insertion_point(struct:DeleteActionReq) */
} DeleteActionReq;

typedef struct _DeleteActionResp {
    int64_t state;
/* @@protoc_insertion_point(struct:DeleteActionResp) */
} DeleteActionResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DeleteActionReq_init_default             {""}
#define DeleteActionResp_init_default            {0}
#define DeleteActionReq_init_zero                {""}
#define DeleteActionResp_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define DeleteActionReq_action_id_tag            1
#define DeleteActionResp_state_tag               1

/* Struct field encoding specification for nanopb */
extern const pb_field_t DeleteActionReq_fields[2];
extern const pb_field_t DeleteActionResp_fields[2];

/* Maximum encoded size of messages (where known) */
#define DeleteActionReq_size                     203
#define DeleteActionResp_size                    11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DELETEACTION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
