/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:16 2018. */

#ifndef PB_DISCONNECT_PB_H_INCLUDED
#define PB_DISCONNECT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DisconnectReq {
    char serial_num[200];
/* @@protoc_insertion_point(struct:DisconnectReq) */
} DisconnectReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DisconnectReq_init_default               {""}
#define DisconnectReq_init_zero                  {""}

/* Field tags (for use in manual encoding/decoding) */
#define DisconnectReq_serial_num_tag             1

/* Struct field encoding specification for nanopb */
extern const pb_field_t DisconnectReq_fields[2];

/* Maximum encoded size of messages (where known) */
#define DisconnectReq_size                       203

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DISCONNECT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
