/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:17 2018. */

#ifndef PB_GETACTIONNAMES_PB_H_INCLUDED
#define PB_GETACTIONNAMES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _GetActionNamesResp {
    pb_size_t name_array_count;
    char name_array[64][200];
/* @@protoc_insertion_point(struct:GetActionNamesResp) */
} GetActionNamesResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define GetActionNamesResp_init_default          {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define GetActionNamesResp_init_zero             {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}

/* Field tags (for use in manual encoding/decoding) */
#define GetActionNamesResp_name_array_tag        1

/* Struct field encoding specification for nanopb */
extern const pb_field_t GetActionNamesResp_fields[2];

/* Maximum encoded size of messages (where known) */
#define GetActionNamesResp_size                  12992

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GETACTIONNAMES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
