/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:17 2018. */

#include "GetActionNames.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t GetActionNamesResp_fields[2] = {
    PB_FIELD(  1, STRING  , REPEATED, STATIC  , FIRST, GetActionNamesResp, name_array, name_array, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
