/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:17 2018. */

#ifndef PB_GETORDERS_PB_H_INCLUDED
#define PB_GETORDERS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _GetOrdersResp {
    pb_size_t order_array_count;
    int64_t order_array[64];
/* @@protoc_insertion_point(struct:GetOrdersResp) */
} GetOrdersResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define GetOrdersResp_init_default               {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define GetOrdersResp_init_zero                  {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define GetOrdersResp_order_array_tag            1

/* Struct field encoding specification for nanopb */
extern const pb_field_t GetOrdersResp_fields[2];

/* Maximum encoded size of messages (where known) */
#define GetOrdersResp_size                       704

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GETORDERS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
