/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:17 2018. */

#include "ModifyAction.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ModifyActionReq_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, ModifyActionReq, action_name, action_name, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, ModifyActionReq, execute_order, action_name, 0),
    PB_FIELD(  3, INT64   , REQUIRED, STATIC  , OTHER, ModifyActionReq, execute_time, execute_order, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, ModifyActionReq, arguments, execute_time, 0),
    PB_LAST_FIELD
};

const pb_field_t ModifyActionResp_fields[2] = {
    PB_FIELD(  1, INT64   , REQUIRED, STATIC  , FIRST, ModifyActionResp, state, state, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
