/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Tue Mar 20 14:40:17 2018. */

#ifndef PB_MODIFYACTION_PB_H_INCLUDED
#define PB_MODIFYACTION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ModifyActionReq {
    char action_name[200];
    int64_t execute_order;
    int64_t execute_time;
    char arguments[200];
/* @@protoc_insertion_point(struct:ModifyActionReq) */
} ModifyActionReq;

typedef struct _ModifyActionResp {
    int64_t state;
/* @@protoc_insertion_point(struct:ModifyActionResp) */
} ModifyActionResp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ModifyActionReq_init_default             {"", 0, 0, ""}
#define ModifyActionResp_init_default            {0}
#define ModifyActionReq_init_zero                {"", 0, 0, ""}
#define ModifyActionResp_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define ModifyActionReq_action_name_tag          1
#define ModifyActionReq_execute_order_tag        2
#define ModifyActionReq_execute_time_tag         3
#define ModifyActionReq_arguments_tag            4
#define ModifyActionResp_state_tag               1

/* Struct field encoding specification for nanopb */
extern const pb_field_t ModifyActionReq_fields[5];
extern const pb_field_t ModifyActionResp_fields[2];

/* Maximum encoded size of messages (where known) */
#define ModifyActionReq_size                     428
#define ModifyActionResp_size                    11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MODIFYACTION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
